/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppCallsRouteImport } from './routes/app.calls'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AppCallsIdRouteImport } from './routes/app.calls.$id'
import { Route as AdminClientsNewRouteImport } from './routes/admin.clients.new'
import { Route as AdminClientsIdRouteImport } from './routes/admin.clients.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AppCallsIdRoute = AppCallsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCallsRoute,
} as any)
const AdminClientsNewRoute = AdminClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminClientsRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/app/calls': typeof AppCallsRouteWithChildren
  '/app/leads': typeof AppLeadsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/app/calls/$id': typeof AppCallsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/app/calls': typeof AppCallsRouteWithChildren
  '/app/leads': typeof AppLeadsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/app/calls/$id': typeof AppCallsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/app/calls': typeof AppCallsRouteWithChildren
  '/app/leads': typeof AppLeadsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/app/calls/$id': typeof AppCallsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/clients'
    | '/admin/settings'
    | '/app/calls'
    | '/app/leads'
    | '/admin/'
    | '/app/'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/app/calls/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/clients'
    | '/admin/settings'
    | '/app/calls'
    | '/app/leads'
    | '/admin'
    | '/app'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/app/calls/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/clients'
    | '/admin/settings'
    | '/app/calls'
    | '/app/leads'
    | '/admin/'
    | '/app/'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/app/calls/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calls': {
      id: '/app/calls'
      path: '/calls'
      fullPath: '/app/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/calls/$id': {
      id: '/app/calls/$id'
      path: '/$id'
      fullPath: '/app/calls/$id'
      preLoaderRoute: typeof AppCallsIdRouteImport
      parentRoute: typeof AppCallsRoute
    }
    '/admin/clients/new': {
      id: '/admin/clients/new'
      path: '/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AdminClientsNewRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminClientsRoute
    }
  }
}

interface AdminClientsRouteChildren {
  AdminClientsIdRoute: typeof AdminClientsIdRoute
  AdminClientsNewRoute: typeof AdminClientsNewRoute
}

const AdminClientsRouteChildren: AdminClientsRouteChildren = {
  AdminClientsIdRoute: AdminClientsIdRoute,
  AdminClientsNewRoute: AdminClientsNewRoute,
}

const AdminClientsRouteWithChildren = AdminClientsRoute._addFileChildren(
  AdminClientsRouteChildren,
)

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCallsRouteChildren {
  AppCallsIdRoute: typeof AppCallsIdRoute
}

const AppCallsRouteChildren: AppCallsRouteChildren = {
  AppCallsIdRoute: AppCallsIdRoute,
}

const AppCallsRouteWithChildren = AppCallsRoute._addFileChildren(
  AppCallsRouteChildren,
)

interface AppRouteChildren {
  AppCallsRoute: typeof AppCallsRouteWithChildren
  AppLeadsRoute: typeof AppLeadsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCallsRoute: AppCallsRouteWithChildren,
  AppLeadsRoute: AppLeadsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
